### ISSUE TITLE
If gitgutter/syntastic not installed, throws an error during operation (but otherwise works ok)

### ISSUE THREAD

**Issue by biwhite** [lightcode/PasteMode.vim#1]
Error throw during toggle/enable/disable, seems to not occur if I install syntastic and gitgutter

```
Error detected while processing function <SNR>61_pastemode_toggle[2]..<SNR>61_pastemode_enable:
line   25:
E171: Missing :endif
```

**Comment by lightcode** [comment]
@biwhite I've pushed a new commit that fixed the issue for me. If the bug persists, you can open the issue again. Thank you.
